version: "1"
services:
  backend:
    image: api-backend
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
  frontend:
    image: client:local
    volumes:
      - $HOME/.aws:/root/.aws
    ports:
      - "3000"
