version: "3"
services:
  # reverseproxy:
  #     image: reverseproxy
  #     ports:
  #         - 8080:8080
  #     restart: always
  #     depends_on:
  #       - api-backend
  backend:
    image: api-backend
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      # POSTGRES_USERNAME: $POSTGRES_USERNAME
      # POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      # POSTGRES_DB: $POSTGRES_DB
      # POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
  frontend:
    image: client:local
    volumes:
      - $HOME/.aws:/root/.aws
    ports:
      - "3000"
